packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  prisma: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.102.2'
  - '@tanstack/query-devtools@5.102.2'
  - '@tanstack/react-query-devtools@5.102.2'
  - '@tanstack/react-query@5.102.2'
  - '@types/react-dom@19.2.5'
  - lucide-react@1.34.0
